1. Split this string
s = "Hi there Sam!" 

In [3]:
s="Hi there Sam!"
print(s.split(" "))

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string.
Output should be: The diameter of Earth is 12742 kilometers.
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {planet} is {diameter} kilometers.".format(planet='Earth',diameter=12742))

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word "hello"
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [30]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
dict1=d['k1'][3]

In [42]:
dict1

{'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}

In [31]:
dict2=dict1['tricky'][3]

In [43]:
dict2

{'target': [1, 2, 3, 'hello']}

In [32]:
dict2['target'][3]

'hello'

4.
4.1 Create an array of 10 zeros?
4.2 Create an array of 10 fives?

In [38]:
import numpy as np
a1=np.arange(10)
a2=np.arange(10)
a1.fill(0)
a2.fill(5)

In [39]:
print(a1)
print(a2)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


5. Create an array of all the even integers from 20 to 35

In [41]:
e=np.arange(20,35,2)
print(e)

[20 22 24 26 28 30 32 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [47]:
m=np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatinate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])[link text](https://)

In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]


8. Create a dataframe with 3 rows and 2 columns

In [50]:
import pandas as pd
r=['a','b','c']
c=[1,2]
l=np.arange(1,7)
l=l.reshape(3,2)
d=pd.DataFrame(l,index=r,columns=c)

In [51]:
d

1  2
a  1  2
b  3  4
c  5  6

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [52]:
pd.date_range(start="2023-01-01",end="2023-02-10")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [53]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)

In [54]:
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24